GCC_WARNING_FLAGS="-Wall -Wextra -pedantic"

CLANG_WARNING_FLAGS="-Weverything -Wno-c++98-compat -Wno-c++98-compat-pedantic \
-Wno-zero-as-null-pointer-constant -Wno-poison-system-directories \
-Wno-weak-vtables -Wno-padded"

SOURCES="\
src/ChessPiece.cpp src/ChessMove.cpp src/ChessBoard.cpp src/CastlingRights.cpp \
src/ChessPosition.cpp src/Utilities.cpp src/ChessEngine.cpp src/ChessGame.cpp \
main.cpp"

GCC_OPT_FLAGS="-DNDEBUG -O3 -march=native -flto=auto"

CLANG_OPT_FLAGS="-DNDEBUG -O3 -mcpu=apple-m1 -flto"

rm -f bin/*

g++-12 -std=c++20 ${GCC_WARNING_FLAGS} ${GCC_OPT_FLAGS} -DSUCKER_CHESS_USE_DETERMINISTIC_SEED ${SOURCES} -o bin/SuckerChessGCC
clang++ -std=c++20 ${CLANG_WARNING_FLAGS} ${CLANG_OPT_FLAGS} -DSUCKER_CHESS_USE_DETERMINISTIC_SEED ${SOURCES} -o bin/SuckerChessClang
g++-12 -std=c++20 ${GCC_WARNING_FLAGS} ${GCC_OPT_FLAGS} -DSUCKER_CHESS_USE_DETERMINISTIC_SEED -DSUCKER_CHESS_USE_COMPRESSED_CHESS_PIECE ${SOURCES} -o bin/SuckerChessGCCP
clang++ -std=c++20 ${CLANG_WARNING_FLAGS} ${CLANG_OPT_FLAGS} -DSUCKER_CHESS_USE_DETERMINISTIC_SEED -DSUCKER_CHESS_USE_COMPRESSED_CHESS_PIECE ${SOURCES} -o bin/SuckerChessClangP
g++-12 -std=c++20 ${GCC_WARNING_FLAGS} ${GCC_OPT_FLAGS} -DSUCKER_CHESS_USE_DETERMINISTIC_SEED -DSUCKER_CHESS_USE_COMPRESSED_CHESS_MOVE ${SOURCES} -o bin/SuckerChessGCCM
clang++ -std=c++20 ${CLANG_WARNING_FLAGS} ${CLANG_OPT_FLAGS} -DSUCKER_CHESS_USE_DETERMINISTIC_SEED -DSUCKER_CHESS_USE_COMPRESSED_CHESS_MOVE ${SOURCES} -o bin/SuckerChessClangM
g++-12 -std=c++20 ${GCC_WARNING_FLAGS} ${GCC_OPT_FLAGS} -DSUCKER_CHESS_USE_DETERMINISTIC_SEED -DSUCKER_CHESS_USE_COMPRESSED_CHESS_PIECE -DSUCKER_CHESS_USE_COMPRESSED_CHESS_MOVE ${SOURCES} -o bin/SuckerChessGCCPM
clang++ -std=c++20 ${CLANG_WARNING_FLAGS} ${CLANG_OPT_FLAGS} -DSUCKER_CHESS_USE_DETERMINISTIC_SEED -DSUCKER_CHESS_USE_COMPRESSED_CHESS_PIECE -DSUCKER_CHESS_USE_COMPRESSED_CHESS_MOVE ${SOURCES} -o bin/SuckerChessClangPM
g++-12 -std=c++20 ${GCC_WARNING_FLAGS} ${GCC_OPT_FLAGS} -DSUCKER_CHESS_USE_DETERMINISTIC_SEED -DSUCKER_CHESS_TRACK_KING_LOCATIONS ${SOURCES} -o bin/SuckerChessGCCK
clang++ -std=c++20 ${CLANG_WARNING_FLAGS} ${CLANG_OPT_FLAGS} -DSUCKER_CHESS_USE_DETERMINISTIC_SEED -DSUCKER_CHESS_TRACK_KING_LOCATIONS ${SOURCES} -o bin/SuckerChessClangK
g++-12 -std=c++20 ${GCC_WARNING_FLAGS} ${GCC_OPT_FLAGS} -DSUCKER_CHESS_USE_DETERMINISTIC_SEED -DSUCKER_CHESS_USE_COMPRESSED_CHESS_PIECE -DSUCKER_CHESS_TRACK_KING_LOCATIONS ${SOURCES} -o bin/SuckerChessGCCPK
clang++ -std=c++20 ${CLANG_WARNING_FLAGS} ${CLANG_OPT_FLAGS} -DSUCKER_CHESS_USE_DETERMINISTIC_SEED -DSUCKER_CHESS_USE_COMPRESSED_CHESS_PIECE -DSUCKER_CHESS_TRACK_KING_LOCATIONS ${SOURCES} -o bin/SuckerChessClangPK
g++-12 -std=c++20 ${GCC_WARNING_FLAGS} ${GCC_OPT_FLAGS} -DSUCKER_CHESS_USE_DETERMINISTIC_SEED -DSUCKER_CHESS_USE_COMPRESSED_CHESS_MOVE -DSUCKER_CHESS_TRACK_KING_LOCATIONS ${SOURCES} -o bin/SuckerChessGCCMK
clang++ -std=c++20 ${CLANG_WARNING_FLAGS} ${CLANG_OPT_FLAGS} -DSUCKER_CHESS_USE_DETERMINISTIC_SEED -DSUCKER_CHESS_USE_COMPRESSED_CHESS_MOVE -DSUCKER_CHESS_TRACK_KING_LOCATIONS ${SOURCES} -o bin/SuckerChessClangMK
g++-12 -std=c++20 ${GCC_WARNING_FLAGS} ${GCC_OPT_FLAGS} -DSUCKER_CHESS_USE_DETERMINISTIC_SEED -DSUCKER_CHESS_USE_COMPRESSED_CHESS_PIECE -DSUCKER_CHESS_USE_COMPRESSED_CHESS_MOVE -DSUCKER_CHESS_TRACK_KING_LOCATIONS ${SOURCES} -o bin/SuckerChessGCCPMK
clang++ -std=c++20 ${CLANG_WARNING_FLAGS} ${CLANG_OPT_FLAGS} -DSUCKER_CHESS_USE_DETERMINISTIC_SEED -DSUCKER_CHESS_USE_COMPRESSED_CHESS_PIECE -DSUCKER_CHESS_USE_COMPRESSED_CHESS_MOVE -DSUCKER_CHESS_TRACK_KING_LOCATIONS ${SOURCES} -o bin/SuckerChessClangPMK
