GCC_WARNING_FLAGS="-Wall -Wextra -pedantic"

CLANG_WARNING_FLAGS="-Weverything -Wno-c++98-compat -Wno-c++98-compat-pedantic \
-Wno-zero-as-null-pointer-constant -Wno-poison-system-directories \
-Wno-weak-vtables -Wno-padded"

SOURCES="\
src/ChessPiece.cpp src/ChessMove.cpp src/ChessBoard.cpp src/CastlingRights.cpp \
src/ChessPosition.cpp src/Utilities.cpp src/ChessEngine.cpp src/UCI.cpp \
src/ChessGame.cpp src/ChessPlayer.cpp src/ChessTournament.cpp main.cpp"

GCC_OPT_FLAGS="-DNDEBUG -O3 -march=native -flto=auto"

CLANG_OPT_FLAGS="-DNDEBUG -O3 -mcpu=apple-m1 -flto"

rm -f bin/*

if [[ "$*" == *"--all"* ]]
then
    g++-12 -std=c++20 ${GCC_WARNING_FLAGS} ${GCC_OPT_FLAGS} -DSUCKER_CHESS_USE_DETERMINISTIC_SEED ${SOURCES} -o bin/SuckerChessGCCD
    clang++ -std=c++20 ${CLANG_WARNING_FLAGS} ${CLANG_OPT_FLAGS} -DSUCKER_CHESS_USE_DETERMINISTIC_SEED ${SOURCES} -o bin/SuckerChessClangD
    g++-12 -std=c++20 ${GCC_WARNING_FLAGS} ${GCC_OPT_FLAGS} -DSUCKER_CHESS_USE_DETERMINISTIC_SEED -DSUCKER_CHESS_USE_COMPRESSED_CHESS_PIECE ${SOURCES} -o bin/SuckerChessGCCDP
    clang++ -std=c++20 ${CLANG_WARNING_FLAGS} ${CLANG_OPT_FLAGS} -DSUCKER_CHESS_USE_DETERMINISTIC_SEED -DSUCKER_CHESS_USE_COMPRESSED_CHESS_PIECE ${SOURCES} -o bin/SuckerChessClangDP
    g++-12 -std=c++20 ${GCC_WARNING_FLAGS} ${GCC_OPT_FLAGS} -DSUCKER_CHESS_USE_DETERMINISTIC_SEED -DSUCKER_CHESS_USE_COMPRESSED_CHESS_MOVE ${SOURCES} -o bin/SuckerChessGCCDM
    clang++ -std=c++20 ${CLANG_WARNING_FLAGS} ${CLANG_OPT_FLAGS} -DSUCKER_CHESS_USE_DETERMINISTIC_SEED -DSUCKER_CHESS_USE_COMPRESSED_CHESS_MOVE ${SOURCES} -o bin/SuckerChessClangDM
    g++-12 -std=c++20 ${GCC_WARNING_FLAGS} ${GCC_OPT_FLAGS} -DSUCKER_CHESS_USE_DETERMINISTIC_SEED -DSUCKER_CHESS_USE_COMPRESSED_CHESS_PIECE -DSUCKER_CHESS_USE_COMPRESSED_CHESS_MOVE ${SOURCES} -o bin/SuckerChessGCCDPM
    clang++ -std=c++20 ${CLANG_WARNING_FLAGS} ${CLANG_OPT_FLAGS} -DSUCKER_CHESS_USE_DETERMINISTIC_SEED -DSUCKER_CHESS_USE_COMPRESSED_CHESS_PIECE -DSUCKER_CHESS_USE_COMPRESSED_CHESS_MOVE ${SOURCES} -o bin/SuckerChessClangDPM
    g++-12 -std=c++20 ${GCC_WARNING_FLAGS} ${GCC_OPT_FLAGS} -DSUCKER_CHESS_USE_DETERMINISTIC_SEED -DSUCKER_CHESS_USE_COMPRESSED_CHESS_BOARD ${SOURCES} -o bin/SuckerChessGCCDB
    clang++ -std=c++20 ${CLANG_WARNING_FLAGS} ${CLANG_OPT_FLAGS} -DSUCKER_CHESS_USE_DETERMINISTIC_SEED -DSUCKER_CHESS_USE_COMPRESSED_CHESS_BOARD ${SOURCES} -o bin/SuckerChessClangDB
    g++-12 -std=c++20 ${GCC_WARNING_FLAGS} ${GCC_OPT_FLAGS} -DSUCKER_CHESS_USE_DETERMINISTIC_SEED -DSUCKER_CHESS_USE_COMPRESSED_CHESS_PIECE -DSUCKER_CHESS_USE_COMPRESSED_CHESS_BOARD ${SOURCES} -o bin/SuckerChessGCCDPB
    clang++ -std=c++20 ${CLANG_WARNING_FLAGS} ${CLANG_OPT_FLAGS} -DSUCKER_CHESS_USE_DETERMINISTIC_SEED -DSUCKER_CHESS_USE_COMPRESSED_CHESS_PIECE -DSUCKER_CHESS_USE_COMPRESSED_CHESS_BOARD ${SOURCES} -o bin/SuckerChessClangDPB
    g++-12 -std=c++20 ${GCC_WARNING_FLAGS} ${GCC_OPT_FLAGS} -DSUCKER_CHESS_USE_DETERMINISTIC_SEED -DSUCKER_CHESS_USE_COMPRESSED_CHESS_MOVE -DSUCKER_CHESS_USE_COMPRESSED_CHESS_BOARD ${SOURCES} -o bin/SuckerChessGCCDMB
    clang++ -std=c++20 ${CLANG_WARNING_FLAGS} ${CLANG_OPT_FLAGS} -DSUCKER_CHESS_USE_DETERMINISTIC_SEED -DSUCKER_CHESS_USE_COMPRESSED_CHESS_MOVE -DSUCKER_CHESS_USE_COMPRESSED_CHESS_BOARD ${SOURCES} -o bin/SuckerChessClangDMB
    g++-12 -std=c++20 ${GCC_WARNING_FLAGS} ${GCC_OPT_FLAGS} -DSUCKER_CHESS_USE_DETERMINISTIC_SEED -DSUCKER_CHESS_USE_COMPRESSED_CHESS_PIECE -DSUCKER_CHESS_USE_COMPRESSED_CHESS_MOVE -DSUCKER_CHESS_USE_COMPRESSED_CHESS_BOARD ${SOURCES} -o bin/SuckerChessGCCDPMB
    clang++ -std=c++20 ${CLANG_WARNING_FLAGS} ${CLANG_OPT_FLAGS} -DSUCKER_CHESS_USE_DETERMINISTIC_SEED -DSUCKER_CHESS_USE_COMPRESSED_CHESS_PIECE -DSUCKER_CHESS_USE_COMPRESSED_CHESS_MOVE -DSUCKER_CHESS_USE_COMPRESSED_CHESS_BOARD ${SOURCES} -o bin/SuckerChessClangDPMB
    g++-12 -std=c++20 ${GCC_WARNING_FLAGS} ${GCC_OPT_FLAGS} -DSUCKER_CHESS_USE_DETERMINISTIC_SEED -DSUCKER_CHESS_TRACK_KING_LOCATIONS ${SOURCES} -o bin/SuckerChessGCCDK
    clang++ -std=c++20 ${CLANG_WARNING_FLAGS} ${CLANG_OPT_FLAGS} -DSUCKER_CHESS_USE_DETERMINISTIC_SEED -DSUCKER_CHESS_TRACK_KING_LOCATIONS ${SOURCES} -o bin/SuckerChessClangDK
    g++-12 -std=c++20 ${GCC_WARNING_FLAGS} ${GCC_OPT_FLAGS} -DSUCKER_CHESS_USE_DETERMINISTIC_SEED -DSUCKER_CHESS_USE_COMPRESSED_CHESS_PIECE -DSUCKER_CHESS_TRACK_KING_LOCATIONS ${SOURCES} -o bin/SuckerChessGCCDPK
    clang++ -std=c++20 ${CLANG_WARNING_FLAGS} ${CLANG_OPT_FLAGS} -DSUCKER_CHESS_USE_DETERMINISTIC_SEED -DSUCKER_CHESS_USE_COMPRESSED_CHESS_PIECE -DSUCKER_CHESS_TRACK_KING_LOCATIONS ${SOURCES} -o bin/SuckerChessClangDPK
    g++-12 -std=c++20 ${GCC_WARNING_FLAGS} ${GCC_OPT_FLAGS} -DSUCKER_CHESS_USE_DETERMINISTIC_SEED -DSUCKER_CHESS_USE_COMPRESSED_CHESS_MOVE -DSUCKER_CHESS_TRACK_KING_LOCATIONS ${SOURCES} -o bin/SuckerChessGCCDMK
    clang++ -std=c++20 ${CLANG_WARNING_FLAGS} ${CLANG_OPT_FLAGS} -DSUCKER_CHESS_USE_DETERMINISTIC_SEED -DSUCKER_CHESS_USE_COMPRESSED_CHESS_MOVE -DSUCKER_CHESS_TRACK_KING_LOCATIONS ${SOURCES} -o bin/SuckerChessClangDMK
    g++-12 -std=c++20 ${GCC_WARNING_FLAGS} ${GCC_OPT_FLAGS} -DSUCKER_CHESS_USE_DETERMINISTIC_SEED -DSUCKER_CHESS_USE_COMPRESSED_CHESS_PIECE -DSUCKER_CHESS_USE_COMPRESSED_CHESS_MOVE -DSUCKER_CHESS_TRACK_KING_LOCATIONS ${SOURCES} -o bin/SuckerChessGCCDPMK
    clang++ -std=c++20 ${CLANG_WARNING_FLAGS} ${CLANG_OPT_FLAGS} -DSUCKER_CHESS_USE_DETERMINISTIC_SEED -DSUCKER_CHESS_USE_COMPRESSED_CHESS_PIECE -DSUCKER_CHESS_USE_COMPRESSED_CHESS_MOVE -DSUCKER_CHESS_TRACK_KING_LOCATIONS ${SOURCES} -o bin/SuckerChessClangDPMK
    g++-12 -std=c++20 ${GCC_WARNING_FLAGS} ${GCC_OPT_FLAGS} -DSUCKER_CHESS_USE_DETERMINISTIC_SEED -DSUCKER_CHESS_USE_COMPRESSED_CHESS_BOARD -DSUCKER_CHESS_TRACK_KING_LOCATIONS ${SOURCES} -o bin/SuckerChessGCCDBK
    clang++ -std=c++20 ${CLANG_WARNING_FLAGS} ${CLANG_OPT_FLAGS} -DSUCKER_CHESS_USE_DETERMINISTIC_SEED -DSUCKER_CHESS_USE_COMPRESSED_CHESS_BOARD -DSUCKER_CHESS_TRACK_KING_LOCATIONS ${SOURCES} -o bin/SuckerChessClangDBK
    g++-12 -std=c++20 ${GCC_WARNING_FLAGS} ${GCC_OPT_FLAGS} -DSUCKER_CHESS_USE_DETERMINISTIC_SEED -DSUCKER_CHESS_USE_COMPRESSED_CHESS_PIECE -DSUCKER_CHESS_USE_COMPRESSED_CHESS_BOARD -DSUCKER_CHESS_TRACK_KING_LOCATIONS ${SOURCES} -o bin/SuckerChessGCCDPBK
    clang++ -std=c++20 ${CLANG_WARNING_FLAGS} ${CLANG_OPT_FLAGS} -DSUCKER_CHESS_USE_DETERMINISTIC_SEED -DSUCKER_CHESS_USE_COMPRESSED_CHESS_PIECE -DSUCKER_CHESS_USE_COMPRESSED_CHESS_BOARD -DSUCKER_CHESS_TRACK_KING_LOCATIONS ${SOURCES} -o bin/SuckerChessClangDPBK
    g++-12 -std=c++20 ${GCC_WARNING_FLAGS} ${GCC_OPT_FLAGS} -DSUCKER_CHESS_USE_DETERMINISTIC_SEED -DSUCKER_CHESS_USE_COMPRESSED_CHESS_MOVE -DSUCKER_CHESS_USE_COMPRESSED_CHESS_BOARD -DSUCKER_CHESS_TRACK_KING_LOCATIONS ${SOURCES} -o bin/SuckerChessGCCDMBK
    clang++ -std=c++20 ${CLANG_WARNING_FLAGS} ${CLANG_OPT_FLAGS} -DSUCKER_CHESS_USE_DETERMINISTIC_SEED -DSUCKER_CHESS_USE_COMPRESSED_CHESS_MOVE -DSUCKER_CHESS_USE_COMPRESSED_CHESS_BOARD -DSUCKER_CHESS_TRACK_KING_LOCATIONS ${SOURCES} -o bin/SuckerChessClangDMBK
    g++-12 -std=c++20 ${GCC_WARNING_FLAGS} ${GCC_OPT_FLAGS} -DSUCKER_CHESS_USE_DETERMINISTIC_SEED -DSUCKER_CHESS_USE_COMPRESSED_CHESS_PIECE -DSUCKER_CHESS_USE_COMPRESSED_CHESS_MOVE -DSUCKER_CHESS_USE_COMPRESSED_CHESS_BOARD -DSUCKER_CHESS_TRACK_KING_LOCATIONS ${SOURCES} -o bin/SuckerChessGCCDPMBK
    clang++ -std=c++20 ${CLANG_WARNING_FLAGS} ${CLANG_OPT_FLAGS} -DSUCKER_CHESS_USE_DETERMINISTIC_SEED -DSUCKER_CHESS_USE_COMPRESSED_CHESS_PIECE -DSUCKER_CHESS_USE_COMPRESSED_CHESS_MOVE -DSUCKER_CHESS_USE_COMPRESSED_CHESS_BOARD -DSUCKER_CHESS_TRACK_KING_LOCATIONS ${SOURCES} -o bin/SuckerChessClangDPMBK
fi

g++-12 -std=c++20 ${GCC_WARNING_FLAGS} ${GCC_OPT_FLAGS} ${SOURCES} -o bin/SuckerChessGCC
clang++ -std=c++20 ${CLANG_WARNING_FLAGS} ${CLANG_OPT_FLAGS} ${SOURCES} -o bin/SuckerChessClang
g++-12 -std=c++20 ${GCC_WARNING_FLAGS} ${GCC_OPT_FLAGS} -DSUCKER_CHESS_USE_COMPRESSED_CHESS_PIECE -DSUCKER_CHESS_USE_COMPRESSED_CHESS_MOVE -DSUCKER_CHESS_USE_COMPRESSED_CHESS_BOARD -DSUCKER_CHESS_TRACK_KING_LOCATIONS ${SOURCES} -o bin/SuckerChessGCCOptimized
clang++ -std=c++20 ${CLANG_WARNING_FLAGS} ${CLANG_OPT_FLAGS} -DSUCKER_CHESS_USE_COMPRESSED_CHESS_PIECE -DSUCKER_CHESS_USE_COMPRESSED_CHESS_MOVE -DSUCKER_CHESS_USE_COMPRESSED_CHESS_BOARD -DSUCKER_CHESS_TRACK_KING_LOCATIONS ${SOURCES} -o bin/SuckerChessClangOptimized
